/**
 * Assembler for neon-seed.sql.
 *
 * Reads:
 *   - /tmp/seed_ddl.sql       (prisma migrate diff output)
 *   - /tmp/seed-inserts.sql   (generated by generate-seed-inserts.ts)
 *
 * Writes:
 *   - /home/z/my-project/scripts/neon-seed.sql
 *
 * The assembler:
 *   1. Prepends a header comment + pgcrypto extension + DROP TABLEs
 *   2. Modifies the DDL to add `DEFAULT gen_random_uuid()::text` to id columns
 *   3. Strips the `CREATE SCHEMA` line (Neon already has public)
 *   4. Strips the `-- AddForeignKey` blocks (we drop with CASCADE — no FK needed)
 *      Actually we keep them — they're fine and they enforce referential integrity
 *   5. Appends the INSERTs
 *   6. Appends a final comment block
 */

import { readFileSync, writeFileSync } from "node:fs";

const DDL_PATH = "/tmp/seed_ddl.sql";
const INSERTS_PATH = "/tmp/seed-inserts.sql";
const OUTPUT_PATH = "/home/z/my-project/scripts/neon-seed.sql";

const ddl = readFileSync(DDL_PATH, "utf8");
const inserts = readFileSync(INSERTS_PATH, "utf8");

// ─── Tables in dependency-safe order (parents before children) ──────────────
const TABLES_IN_ORDER = [
  // Independent / referenced by others
  "AdminUser",
  "Category",
  "Industry",
  "Solution",
  // References Category
  "Service",
  // Independent content
  "Project",
  "BlogPost",
  "Testimonial",
  "Faq",
  "CompanySettings",
  "PageContent",
  "Redirect",
  "Media",
  // References AdminUser (FK)
  "AuditLog",
  // Independent (no FKs)
  "Lead",
];

// ─── Transform DDL ──────────────────────────────────────────────────────────

// 1) Drop the CREATE SCHEMA line (Neon already has public)
let ddlLines = ddl.split("\n").filter((line) => {
  if (line.trim().startsWith("CREATE SCHEMA")) return false;
  if (line.trim() === "" && ddl.split("\n").indexOf(line) > 0) {
    // Keep blank lines but not the leading ones
    return true;
  }
  return true;
});

// Remove the first -- comment block (Drizzle adds a "-- CreateSchema" header)
ddlLines = ddlLines.filter((line, i) => {
  // Skip the first "-- CreateSchema" comment
  if (i === 0 && line.startsWith("-- CreateSchema")) return false;
  return true;
});

// 2) Add `DEFAULT gen_random_uuid()::text` to id columns
//    Matches: `"id" TEXT NOT NULL,` (the column declaration line)
ddlLines = ddlLines.map((line) => {
  const trimmed = line.trim();
  // Match the id column declaration: "id" TEXT NOT NULL,
  if (/^"id" TEXT NOT NULL,?\s*$/.test(trimmed)) {
    const indent = line.match(/^(\s*)/)?.[1] ?? "";
    const trailingComma = trimmed.endsWith(",") ? "," : "";
    return `${indent}"id" TEXT NOT NULL DEFAULT gen_random_uuid()::text${trailingComma}`;
  }
  return line;
});

// 3) Convert "ALTER TABLE ... ADD CONSTRAINT ... FOREIGN KEY" lines to use
//    IF NOT EXISTS (so the script can be re-run safely if desired).
//    Actually — we DROP everything first, so this is unnecessary. Keep as-is.

const ddlText = ddlLines.join("\n");

// ─── Build header ───────────────────────────────────────────────────────────

const header = `-- ============================================================
--  ALLISON GLOBAL — COMPLETE NEON SQL SCRIPT
--  Drop everything, create all tables (matching prisma/schema.prisma),
--  seed all content, and create the first superadmin user.
--
--  HOW TO USE:
--  1. Open your Neon project → SQL Editor
--  2. Paste this entire script
--  3. Run it
--  4. Log in at /admin/login with:
--     Email:    admin@allisonglobal.tech
--     Password: Admin@2025
--  5. CHANGE THE PASSWORD immediately after first login
--     via /admin → Settings or the password change API
--
--  NOTE: This script is the ONLY database initialization script.
--        It must create ALL tables and seed ALL content from the
--        static data files in src/lib/data/.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ═══════════════════════════════════════════════════════════
--  DROP EVERYTHING (clean slate)
--  Order: child tables first (AuditLog → AdminUser), then parents.
--  CASCADE ensures constraints + dependent objects are dropped.
-- ═══════════════════════════════════════════════════════════
${TABLES_IN_ORDER.slice().reverse().map((t) => `DROP TABLE IF EXISTS "${t}" CASCADE;`).join("\n")}
DROP TABLE IF EXISTS "_prisma_migrations" CASCADE;

-- ═══════════════════════════════════════════════════════════
--  CREATE TABLES & INDEXES (matches prisma/schema.prisma)
-- ═══════════════════════════════════════════════════════════

`;

// ─── Build footer ───────────────────────────────────────────────────────────

const footer = `
-- ═══════════════════════════════════════════════════════════
--  LOGIN INSTRUCTIONS
-- ═══════════════════════════════════════════════════════════
--  After running this script, log in to the admin panel at:
--
--    https://<your-domain>/admin/login
--
--  With:
--    Email:    admin@allisonglobal.tech
--    Password: Admin@2025
--
--  IMPORTANT: Change the password immediately after first login.
--
--  Tables created (15):
--    AdminUser, AuditLog, Lead, Category, Service, Project,
--    BlogPost, Industry, Testimonial, Faq, Solution,
--    CompanySettings, PageContent, Redirect, Media
--
--  Content seeded:
--    1 AdminUser (superadmin)
--    6 Categories (with slug as id)
--    26 Services (with slug as id)
--    13 Industries (id = slug = old id, e.g. 'corporate', 'retail')
--    9 Projects (slug generated from title)
--    6 BlogPosts (status=published)
--    6 Solutions (slug generated from name)
--    8 Testimonials (published=true)
--    16 FAQs (published=true)
--    12 CompanySettings keys:
--      company, navigation, process, jobs, careers,
--      legal_privacy, legal_terms, stats, values, guarantees,
--      technologyPlatforms, differentiators
--    0 PageContent (empty — populate via admin)
--    0 Redirect (empty — populate via admin)
--    0 Media (empty — populate via admin)
-- ═══════════════════════════════════════════════════════════
`;

// ─── Assemble ────────────────────────────────────────────────────────────────

const finalSql = header + ddlText + "\n\n-- ═══════════════════════════════════════════════════════════\n--  SEED CONTENT\n-- ═══════════════════════════════════════════════════════════\n\n" + inserts + footer;

writeFileSync(OUTPUT_PATH, finalSql, "utf8");
console.log(`✓ Wrote ${OUTPUT_PATH}`);
console.log(`  Total lines: ${finalSql.split("\n").length}`);
console.log(`  Total bytes: ${finalSql.length}`);
