-- ============================================================
--  ALLISON GLOBAL — COMPLETE NEON SQL SCRIPT
--  Drop everything, create all tables, seed all content,
--  and create the first superadmin user.
--
--  HOW TO USE:
--  1. Open your Neon project → SQL Editor
--  2. Paste this entire script
--  3. Run it
--  4. Log in at /admin/login with:
--     Email:    admin@allisonglobal.tech
--     Password: Admin@2025
--  5. CHANGE THE PASSWORD immediately after first login
--     via /admin → Settings or the password change API
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ═══════════════════════════════════════════════════════════
--  DROP EVERYTHING (clean slate)
-- ═══════════════════════════════════════════════════════════
DROP TABLE IF EXISTS "AuditLog" CASCADE;
DROP TABLE IF EXISTS "Lead" CASCADE;
DROP TABLE IF EXISTS "Service" CASCADE;
DROP TABLE IF EXISTS "Category" CASCADE;
DROP TABLE IF EXISTS "Project" CASCADE;
DROP TABLE IF EXISTS "BlogPost" CASCADE;
DROP TABLE IF EXISTS "Industry" CASCADE;
DROP TABLE IF EXISTS "Testimonial" CASCADE;
DROP TABLE IF EXISTS "Faq" CASCADE;
DROP TABLE IF EXISTS "Solution" CASCADE;
DROP TABLE IF EXISTS "CompanySettings" CASCADE;
DROP TABLE IF EXISTS "AdminUser" CASCADE;
DROP TABLE IF EXISTS "_prisma_migrations" CASCADE;

-- ═══════════════════════════════════════════════════════════
--  CREATE TABLES
-- ═══════════════════════════════════════════════════════════

CREATE TABLE "AdminUser" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "email" TEXT NOT NULL UNIQUE,
    "passwordHash" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'admin',
    "active" BOOLEAN NOT NULL DEFAULT true,
    "lastLogin" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "AdminUser_email_idx" ON "AdminUser"("email");
CREATE INDEX "AdminUser_role_idx" ON "AdminUser"("role");

CREATE TABLE "AuditLog" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "userId" TEXT,
    "action" TEXT NOT NULL,
    "resource" TEXT NOT NULL,
    "resourceId" TEXT,
    "metadata" JSONB,
    "ip" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "AdminUser"("id") ON DELETE SET NULL
);
CREATE INDEX "AuditLog_userId_idx" ON "AuditLog"("userId");
CREATE INDEX "AuditLog_action_idx" ON "AuditLog"("action");
CREATE INDEX "AuditLog_resource_idx" ON "AuditLog"("resource");
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");

CREATE TABLE "Lead" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "type" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT,
    "company" TEXT,
    "industry" TEXT,
    "subject" TEXT,
    "services" TEXT,
    "budget" TEXT,
    "timeline" TEXT,
    "message" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'new',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "Lead_email_idx" ON "Lead"("email");
CREATE INDEX "Lead_status_idx" ON "Lead"("status");
CREATE INDEX "Lead_type_idx" ON "Lead"("type");
CREATE INDEX "Lead_createdAt_idx" ON "Lead"("createdAt");
CREATE INDEX "Lead_status_createdAt_idx" ON "Lead"("status", "createdAt");

CREATE TABLE "Category" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "slug" TEXT NOT NULL UNIQUE,
    "name" TEXT NOT NULL,
    "tagline" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "iconName" TEXT NOT NULL,
    "accent" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "Category_slug_idx" ON "Category"("slug");
CREATE INDEX "Category_sortOrder_idx" ON "Category"("sortOrder");

CREATE TABLE "Service" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "slug" TEXT NOT NULL UNIQUE,
    "name" TEXT NOT NULL,
    "categoryId" TEXT NOT NULL,
    "tagline" TEXT NOT NULL,
    "shortDescription" TEXT NOT NULL,
    "overview" TEXT NOT NULL,
    "problem" JSONB NOT NULL,
    "solution" TEXT NOT NULL,
    "deliverables" JSONB NOT NULL,
    "benefits" JSONB NOT NULL,
    "tech" JSONB NOT NULL,
    "relatedServices" JSONB NOT NULL,
    "relatedIndustries" JSONB NOT NULL,
    "faqs" JSONB,
    "featured" BOOLEAN NOT NULL DEFAULT false,
    "published" BOOLEAN NOT NULL DEFAULT true,
    "iconName" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Service_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id")
);
CREATE INDEX "Service_slug_idx" ON "Service"("slug");
CREATE INDEX "Service_categoryId_idx" ON "Service"("categoryId");
CREATE INDEX "Service_published_idx" ON "Service"("published");
CREATE INDEX "Service_featured_idx" ON "Service"("featured");
CREATE INDEX "Service_sortOrder_idx" ON "Service"("sortOrder");

CREATE TABLE "Project" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "title" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "industry" TEXT NOT NULL,
    "services" JSONB NOT NULL,
    "location" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "highlights" JSONB NOT NULL,
    "imageQuery" TEXT NOT NULL,
    "year" TEXT NOT NULL,
    "featured" BOOLEAN NOT NULL DEFAULT false,
    "published" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "Project_category_idx" ON "Project"("category");
CREATE INDEX "Project_industry_idx" ON "Project"("industry");
CREATE INDEX "Project_published_idx" ON "Project"("published");
CREATE INDEX "Project_featured_idx" ON "Project"("featured");
CREATE INDEX "Project_createdAt_idx" ON "Project"("createdAt");

CREATE TABLE "BlogPost" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "slug" TEXT NOT NULL UNIQUE,
    "title" TEXT NOT NULL,
    "excerpt" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "readTime" TEXT NOT NULL,
    "date" TEXT NOT NULL,
    "author" TEXT NOT NULL,
    "authorRole" TEXT NOT NULL,
    "imageQuery" TEXT NOT NULL,
    "content" JSONB NOT NULL,
    "tags" JSONB NOT NULL,
    "featured" BOOLEAN NOT NULL DEFAULT false,
    "published" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "BlogPost_slug_idx" ON "BlogPost"("slug");
CREATE INDEX "BlogPost_category_idx" ON "BlogPost"("category");
CREATE INDEX "BlogPost_published_idx" ON "BlogPost"("published");
CREATE INDEX "BlogPost_featured_idx" ON "BlogPost"("featured");
CREATE INDEX "BlogPost_date_idx" ON "BlogPost"("date");

CREATE TABLE "Industry" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "name" TEXT NOT NULL,
    "tagline" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "challenges" JSONB NOT NULL,
    "solutions" JSONB NOT NULL,
    "outcomes" JSONB NOT NULL,
    "imageQuery" TEXT NOT NULL,
    "iconName" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "Industry_name_idx" ON "Industry"("name");
CREATE INDEX "Industry_sortOrder_idx" ON "Industry"("sortOrder");

CREATE TABLE "Testimonial" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "quote" TEXT NOT NULL,
    "authorRole" TEXT NOT NULL,
    "sector" TEXT NOT NULL,
    "rating" INTEGER NOT NULL DEFAULT 5,
    "projectType" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "Testimonial_sector_idx" ON "Testimonial"("sector");
CREATE INDEX "Testimonial_createdAt_idx" ON "Testimonial"("createdAt");

CREATE TABLE "Faq" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "category" TEXT NOT NULL,
    "question" TEXT NOT NULL,
    "answer" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "Faq_category_idx" ON "Faq"("category");
CREATE INDEX "Faq_sortOrder_idx" ON "Faq"("sortOrder");

CREATE TABLE "Solution" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "name" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "components" JSONB NOT NULL,
    "outcomes" JSONB NOT NULL,
    "bestFor" JSONB NOT NULL,
    "iconName" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "Solution_name_idx" ON "Solution"("name");
CREATE INDEX "Solution_sortOrder_idx" ON "Solution"("sortOrder");

CREATE TABLE "CompanySettings" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "key" TEXT NOT NULL UNIQUE,
    "value" JSONB NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "CompanySettings_key_idx" ON "CompanySettings"("key");

-- ═══════════════════════════════════════════════════════════
--  SEED: ADMIN USER
--  Email:    admin@allisonglobal.tech
--  Password: Admin@2025
--  ⚠️  CHANGE THIS PASSWORD after first login!
-- ═══════════════════════════════════════════════════════════
INSERT INTO "AdminUser" ("email", "passwordHash", "name", "role", "active") VALUES
('admin@allisonglobal.tech', '$2b$10$LHDK6oERJRvKCZilhON4f.30mERAr1u670ChIH0JFDaATtFXY9ss2', 'Agu Chisom Alvin', 'superadmin', true)
ON CONFLICT ("email") DO UPDATE SET "passwordHash" = EXCLUDED."passwordHash", "name" = EXCLUDED."name", "role" = EXCLUDED."role", "active" = true, "updatedAt" = CURRENT_TIMESTAMP;

-- ═══════════════════════════════════════════════════════════
--  SEED: CATEGORIES (6)
-- ═══════════════════════════════════════════════════════════
INSERT INTO "Category" ("slug", "name", "tagline", "description", "iconName", "accent", "sortOrder") VALUES
('network-connectivity', 'Network & Connectivity', 'The backbone everything else runs on', 'Structured cabling, switching, routing and wireless engineered for performance, reliability and future growth.', 'Network', 'from-emerald-500/20 to-teal-500/10', 1),
('cybersecurity', 'Cybersecurity', 'Protect your data, network and endpoints', 'Defend your business against intrusion, malware, ransomware and data loss with layered security.', 'ShieldCheck', 'from-teal-500/20 to-emerald-500/10', 2),
('surveillance-monitoring', 'Surveillance & Monitoring', 'See everything that matters', 'CCTV and IP video systems designed for coverage, clarity and reliable playback.', 'Camera', 'from-amber-500/20 to-emerald-500/10', 3),
('access-control', 'Access Control & Automation', 'Control who enters, when and where', 'Card, biometric and intercom systems that secure doors, gates and sensitive areas.', 'Fingerprint', 'from-emerald-500/20 to-amber-500/10', 4),
('alarm-fire-safety', 'Alarm & Fire Safety', 'Early warning that saves lives and assets', 'Intrusion alarms, fire detection and life-safety systems engineered to standards.', 'Flame', 'from-orange-500/20 to-amber-500/10', 5),
('it-infrastructure', 'IT Infrastructure & Support', 'Resilient systems, always-on support', 'Servers, data-centre fit-out, computer support and managed services.', 'ServerCog', 'from-teal-500/20 to-slate-500/10', 6)
ON CONFLICT ("slug") DO UPDATE SET "name" = EXCLUDED."name", "tagline" = EXCLUDED."tagline", "description" = EXCLUDED."description", "iconName" = EXCLUDED."iconName", "accent" = EXCLUDED."accent", "updatedAt" = CURRENT_TIMESTAMP;

-- ═══════════════════════════════════════════════════════════
--  SEED: INDUSTRIES (13)
-- ═══════════════════════════════════════════════════════════
INSERT INTO "Industry" ("id", "name", "tagline", "summary", "challenges", "solutions", "outcomes", "imageQuery", "iconName", "sortOrder") VALUES
('residential', 'Residential & Estates', 'Secure homes and residential estates', 'Smart, reliable security for homes and estates.', '["Perimeter and entry-point security","Reliable Wi-Fi coverage","Fire and intrusion detection","Access control for gates and staff"]'::jsonb, '["cctv-installation","access-control-systems","burglar-alarm-systems","intercom-systems","wifi-installation","fire-alarm-systems"]'::jsonb, '["Visible deterrent and evidence","Controlled access for family and staff","Reliable connectivity","Early warning for intrusion and fire"]'::jsonb, 'modern smart home security camera and gate at dusk', 'Home', 1),
('corporate', 'Corporate Offices', 'Secure, connected, productive workplaces', 'Enterprise networking, cybersecurity, access control and surveillance.', '["Secure segmented networks","Access control with audit trails","Cybersecurity defending data","Surveillance across premises"]'::jsonb, '["lan-wan","network-security","access-control-systems","cctv-installation","firewall-endpoint-protection","managed-services"]'::jsonb, '["Resilient segmented network","Controlled audited access","Defended data and endpoints","Monitored premises"]'::jsonb, 'modern corporate office building with security and networking', 'Building2', 2),
('education', 'Schools & Universities', 'Safe, connected campuses for learning', 'Campus-wide networking, surveillance, access control and cybersecurity.', '["Campus-wide Wi-Fi and network","Surveillance across large campuses","Access control for labs and dorms","Cybersecurity protecting student data"]'::jsonb, '["wifi-installation","lan-wan","cctv-installation","access-control-systems","network-security","fire-alarm-systems"]'::jsonb, '["Reliable connectivity","Safer monitored campuses","Controlled access to sensitive areas","Protected institutional data"]'::jsonb, 'university campus with security cameras and networking', 'GraduationCap', 3),
('healthcare', 'Hospitals & Healthcare', 'Life-safety and data protection for healthcare', 'Fire safety, access control, surveillance and resilient IT.', '["Fire detection and life-safety compliance","Access control for pharmacies and records","Surveillance for patient and staff safety","Resilient IT and data protection"]'::jsonb, '["fire-alarm-systems","access-control-systems","cctv-installation","server-data-centre","network-security","managed-services"]'::jsonb, '["Compliant life-safety systems","Controlled access to sensitive areas","Monitored premises for safety","Resilient protected patient data"]'::jsonb, 'modern hospital corridor with safety and security systems', 'Stethoscope', 4),
('hospitality', 'Hotels & Hospitality', 'Guest experience built on security', 'Surveillance, access control, fire safety and seamless Wi-Fi.', '["Guest Wi-Fi isolated from operations","Access control for rooms and floors","Surveillance of public and service areas","Fire safety across guest floors and kitchens"]'::jsonb, '["wifi-installation","access-control-systems","cctv-installation","fire-alarm-systems","intercom-systems","network-security"]'::jsonb, '["Seamless secure guest connectivity","Controlled access across property","Safer guests and staff","Compliant fire and life safety"]'::jsonb, 'modern hotel lobby with discreet security and access systems', 'Hotel', 5),
('retail', 'Retail Stores', 'Loss prevention and connected retail', 'CCTV, alarms, access control and networking.', '["Shrinkage and theft at point of sale","Alarm and intrusion detection out of hours","Multi-site surveillance and viewing","Reliable POS and inventory network"]'::jsonb, '["cctv-installation","burglar-alarm-systems","access-control-systems","lan-wan","video-monitoring","perimeter-intrusion"]'::jsonb, '["Reduced shrinkage and clearer evidence","Early intrusion detection and alerts","Multi-site oversight","Reliable retail network"]'::jsonb, 'retail store interior with discreet security cameras', 'ShoppingBag', 6),
('warehouse', 'Warehouses & Logistics', 'Protect inventory and operations', 'Perimeter and surveillance systems, access control and resilient networking.', '["Large perimeters hard to monitor","Inventory theft and stock movement tracking","Access control for staff and vehicles","Resilient network across large facilities"]'::jsonb, '["perimeter-intrusion","cctv-installation","access-control-systems","structured-cabling","burglar-alarm-systems","fire-alarm-systems"]'::jsonb, '["Early perimeter detection","Clear surveillance of inventory","Controlled access for people and vehicles","Resilient operations network"]'::jsonb, 'large warehouse logistics facility with perimeter security cameras', 'Warehouse', 7),
('industrial', 'Manufacturing & Industrial', 'Secure and resilient industrial operations', 'Rugged networking, perimeter security, surveillance and fire safety.', '["Harsh environments defeating standard equipment","Large perimeters and high-value assets","Fire and safety compliance","Networks spanning large facilities"]'::jsonb, '["perimeter-intrusion","cctv-installation","fire-detection-safety","structured-cabling","access-control-systems","network-installation"]'::jsonb, '["Rugged reliable security infrastructure","Protected perimeters and assets","Compliant fire and life safety","Resilient industrial networks"]'::jsonb, 'industrial manufacturing plant with perimeter security systems', 'Factory', 8),
('construction', 'Construction Sites', 'Temporary security that works', 'Mobile surveillance, perimeter detection and alarms.', '["Theft of materials and equipment","Temporary perimeters that change","No fixed infrastructure","Need for remote monitoring"]'::jsonb, '["cctv-installation","video-monitoring","perimeter-intrusion","burglar-alarm-systems","wifi-installation"]'::jsonb, '["Deterrent and evidence against theft","Flexible security that adapts","Remote monitoring without infrastructure","Lower losses during construction"]'::jsonb, 'construction site with mobile security cameras and barriers at night', 'HardHat', 9),
('government', 'Government & Public Sector', 'Secure and compliant public infrastructure', 'Security and IT infrastructure for government and public institutions.', '["Strict compliance and audit requirements","Protection of sensitive public data","Controlled access to facilities","Resilient reliable infrastructure"]'::jsonb, '["network-security","access-control-systems","cctv-installation","security-assessment","server-data-centre","fire-alarm-systems"]'::jsonb, '["Compliant auditable security posture","Protected sensitive data","Controlled monitored access","Resilient public-sector infrastructure"]'::jsonb, 'government building with security and access control systems', 'Landmark', 10),
('religious', 'Religious Organizations', 'Safe, welcoming places of worship', 'Surveillance, access control, fire safety and AV networking.', '["Surveillance of large gathering spaces","Access control for offices and valuables","Fire safety for crowded gatherings","AV and network for services"]'::jsonb, '["cctv-installation","access-control-systems","fire-alarm-systems","wifi-installation","intercom-systems","burglar-alarm-systems"]'::jsonb, '["Safer gatherings and premises","Controlled access to sensitive areas","Compliant fire safety","Connected services and outreach"]'::jsonb, 'large place of worship interior with discreet security systems', 'Church', 11),
('finance', 'Financial Institutions', 'Security and compliance for finance', 'Cybersecurity, surveillance, access control and resilient IT.', '["Stringent regulatory demands","Protection of financial data","Surveillance and access for branches and vaults","Resilient always-on IT infrastructure"]'::jsonb, '["network-security","firewall-endpoint-protection","cctv-installation","access-control-systems","server-data-centre","security-assessment"]'::jsonb, '["Defensible compliant security posture","Protected financial data","Controlled surveilled facilities","Resilient recoverable infrastructure"]'::jsonb, 'modern bank interior with security cameras and access control', 'PiggyBank', 12),
('smb', 'Small & Medium Businesses', 'Enterprise-grade security, right-sized', 'Right-sized networking, security and IT support.', '["Limited in-house IT expertise","Need for protection without big budgets","Reliable IT support without a full team","Scalable systems that grow"]'::jsonb, '["managed-services","computer-it-support","network-installation","cctv-installation","firewall-endpoint-protection","wifi-installation"]'::jsonb, '["Professional IT and security without in-house team","Predictable manageable costs","Reliable day-to-day operations","Systems that scale with growth"]'::jsonb, 'small business office with networking and security systems', 'Store', 13)
ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "tagline" = EXCLUDED."tagline", "summary" = EXCLUDED."summary", "challenges" = EXCLUDED."challenges", "solutions" = EXCLUDED."solutions", "outcomes" = EXCLUDED."outcomes", "imageQuery" = EXCLUDED."imageQuery", "iconName" = EXCLUDED."iconName", "updatedAt" = CURRENT_TIMESTAMP;

-- ═══════════════════════════════════════════════════════════
--  SEED: SOLUTIONS (6)
-- ═══════════════════════════════════════════════════════════
INSERT INTO "Solution" ("id", "name", "summary", "description", "components", "outcomes", "bestFor", "iconName", "sortOrder") VALUES
('unified-security', 'Unified Security & Surveillance', 'CCTV, access control, alarms and monitoring integrated into one security platform.', 'We integrate surveillance, access control, alarms and monitoring into one platform so your security works as a single, responsive system.', '["cctv-installation","access-control-systems","burglar-alarm-systems","video-monitoring","perimeter-intrusion"]'::jsonb, '["Incidents detected, recorded and alerted in one flow","Single platform instead of disconnected systems","Faster, better-coordinated response","Clearer evidence and audit trails"]'::jsonb, '["corporate","warehouse","industrial","retail","residential"]'::jsonb, 'ShieldCheck', 1),
('resilient-network', 'Resilient Network Infrastructure', 'Cabling, switching, routing and Wi-Fi engineered for performance, security and growth.', 'We engineer a resilient network foundation with structured cabling, managed switching, segmentation and wireless.', '["structured-cabling","lan-wan","wifi-installation","network-installation","network-maintenance"]'::jsonb, '["Reliable connectivity for every system and user","Clean segmentation of voice, data, surveillance and guests","Future-proofed headroom for growth","Documented, supportable infrastructure"]'::jsonb, '["corporate","education","healthcare","industrial","hospitality"]'::jsonb, 'Network', 2),
('cyber-defence', 'Cyber Defence Programme', 'Layered cybersecurity — assessment, firewalls, endpoint protection and monitoring.', 'We build a layered cyber-defence programme — assessment, next-gen firewalls, endpoint protection, intrusion detection and ongoing monitoring.', '["security-assessment","network-security","firewall-endpoint-protection","intrusion-detection","managed-services"]'::jsonb, '["Defensible, documented security posture","Blocked malware, ransomware and intrusion attempts","Visibility and alerting on threats","Stronger compliance position"]'::jsonb, '["finance","corporate","government","healthcare","smb"]'::jsonb, 'ShieldCheck', 3),
('life-safety', 'Life Safety & Fire Protection', 'Fire detection, alarm and safety systems engineered for compliance and rapid evacuation.', 'We engineer comprehensive fire detection, alarm and safety solutions — detectors, call points, sounders, emergency lighting and integration.', '["fire-alarm-systems","fire-detection-safety","door-access-systems","managed-services"]'::jsonb, '["Early, reliable fire detection","Compliant, insurable life-safety systems","Safe, coordinated evacuation","Documented for inspection"]'::jsonb, '["hospitality","healthcare","education","industrial","warehouse"]'::jsonb, 'Flame', 4),
('smart-building', 'Smart Building Integration', 'Security, automation, lighting and energy unified into one manageable platform.', 'We integrate security, access, surveillance, lighting, climate and energy into one smart-building platform.', '["smart-building-solutions","access-control-systems","intercom-systems","cctv-installation","wifi-installation"]'::jsonb, '["Simpler, smarter building operations","Lower energy costs through automation","Better security and comfort","One interface instead of many"]'::jsonb, '["corporate","hospitality","residential","government","healthcare"]'::jsonb, 'Building2', 5),
('managed-it', 'Managed IT & Security', 'Your IT and security under continuous care — monitoring, maintenance and support.', 'We manage your IT and security under one agreement — proactive monitoring, preventive maintenance, priority support and ongoing improvement.', '["managed-services","computer-it-support","network-maintenance","network-security","systems-installation-maintenance"]'::jsonb, '["Predictable costs, fewer surprises","Healthier systems that fail less","Faster, prioritised response","A strategic partner, not just a vendor"]'::jsonb, '["corporate","smb","finance","healthcare","education"]'::jsonb, 'ServerCog', 6)
ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "summary" = EXCLUDED."summary", "description" = EXCLUDED."description", "components" = EXCLUDED."components", "outcomes" = EXCLUDED."outcomes", "bestFor" = EXCLUDED."bestFor", "iconName" = EXCLUDED."iconName", "updatedAt" = CURRENT_TIMESTAMP;

-- ═══════════════════════════════════════════════════════════
--  SEED: COMPANY SETTINGS
-- ═══════════════════════════════════════════════════════════
INSERT INTO "CompanySettings" ("key", "value") VALUES
('company', '{"name":"Allison Global","legalName":"Allison Global Ltd","tagline":"Technology without limits.","foundedYear":"2025","foundedLabel":"Established October 2025","rcNumber":"RC: 8939118","shortPitch":"A Nigerian technology and security solutions partner. We assess, design, supply, install, integrate and maintain the systems that keep your people, data and property secure — under one accountable team.","longPitch":"Allison Global Ltd is a technology and security solutions partner serving homes, offices, businesses, institutions and industries across Nigeria. We bring together ICT, networking, cybersecurity and electronic security under one engineering-led team — so your infrastructure, surveillance, access control and fire safety systems are designed to work as one, not as isolated products. From the first site assessment to long-term managed support, we own the outcome.","location":{"city":"Lagos","country":"Nigeria","coverage":"Headquartered in Lagos, delivering projects nationwide with rapid-response support across major Nigerian cities.","addressLine":"Lagos, Nigeria"},"contact":{"phone":"09152158801","phoneDisplay":"+234 915 215 8801","phoneIntl":"+2349152158801","email":"hello@allisonglobal.tech","salesEmail":"sales@allisonglobal.tech","supportEmail":"support@allisonglobal.tech","whatsapp":"2349152158801","hours":"Mon–Sat: 8:00am – 6:00pm · Emergency support 24/7"},"social":{"linkedin":"#","facebook":"#","instagram":"#","x":"#"},"founder":{"name":"Agu Chisom Alvin","title":"Founder & Chief Executive Officer","discipline":"Electrical & Electronics Engineer","bio":"Agu Chisom Alvin is an Electrical & Electronics Engineer who founded Allison Global Ltd in October 2025 to close a gap he kept seeing on site: organisations buying good equipment, then losing value because nobody engineered the whole system end-to-end. He leads Allison Global with a field-first, engineering-led approach — every project is treated as a system, not a shopping list, and every client gets a single accountable partner from assessment through to long-term support.","phone":"09152158801"}}'::jsonb)
ON CONFLICT ("key") DO UPDATE SET "value" = EXCLUDED."value", "updatedAt" = CURRENT_TIMESTAMP;

-- ═══════════════════════════════════════════════════════════
--  SEED: TESTIMONIALS (8)
-- ═══════════════════════════════════════════════════════════
INSERT INTO "Testimonial" ("id", "quote", "authorRole", "sector", "rating", "projectType") VALUES
('t1', 'Allison Global treated our office network and security as one system, not separate purchases. The handover documentation alone was better than anything we had from previous vendors.', 'Operations Manager', 'corporate', 5, 'Network & Cybersecurity Build'),
('t2', 'After we rolled out their CCTV and alarm package across our branches, after-hours losses dropped noticeably. Being able to view every store from one app changed how we manage security.', 'Retail Operations Lead', 'retail', 5, 'Multi-Site Surveillance & Alarms'),
('t3', 'The fire alarm and access control integration gave us real confidence for evacuation compliance. They did not just install — they explained, trained our team, and stayed for support.', 'Facilities Manager', 'hospitality', 5, 'Fire Safety & Access Integration'),
('t4', 'Our perimeter had been a problem for years. Their beam detection and triggered cameras finally gave us early warning instead of discovering break-ins the next morning.', 'Warehouse Supervisor', 'warehouse', 5, 'Perimeter & Inventory Protection'),
('t5', 'Our server room was a mess before Allison Global rebuilt it. Proper racks, UPS, cooling and backup — and they have managed it since. Downtime basically stopped being a worry.', 'IT Lead', 'healthcare', 5, 'Server Room & Managed IT'),
('t6', 'What stood out was the honesty. They told us where we were overspending and where we genuinely needed more. That kind of counsel is rare with vendors.', 'Business Owner', 'smb', 5, 'Security Assessment & IT Support'),
('t7', 'As a growing school, we needed campus Wi-Fi and surveillance done properly. They heat-mapped everything and the coverage is the best we have ever had.', 'School Administrator', 'education', 5, 'Campus Wi-Fi & Surveillance'),
('t8', 'Gate access control with video intercoms transformed how our estate handles visitors. Residents feel safer and management finally has proper records of who comes and goes.', 'Estate Facility Manager', 'residential', 5, 'Estate Access & Smart Security')
ON CONFLICT ("id") DO UPDATE SET "quote" = EXCLUDED."quote", "authorRole" = EXCLUDED."authorRole", "sector" = EXCLUDED."sector", "rating" = EXCLUDED."rating", "projectType" = EXCLUDED."projectType", "updatedAt" = CURRENT_TIMESTAMP;

-- ═══════════════════════════════════════════════════════════
--  SEED: PROJECTS (9)
-- ═══════════════════════════════════════════════════════════
INSERT INTO "Project" ("id", "title", "category", "industry", "services", "location", "scope", "description", "highlights", "imageQuery", "year", "featured") VALUES
('p-001', 'Multi-Site Retail Surveillance & Alarm Rollout', 'Surveillance & Alarms', 'retail', '["cctv-installation","burglar-alarm-systems","video-monitoring","lan-wan"]'::jsonb, 'Lagos & Ogun', '8 retail locations · unified monitoring', 'A regional retail chain needed consistent surveillance and intrusion detection across eight branches.', '["Standardised CCTV and alarms across 8 branches","Centralised multi-site monitoring platform","Out-of-hours intrusion alerts to management","Reduced shrinkage and faster incident review"]'::jsonb, 'retail store surveillance camera system installation', '2025', true),
('p-002', 'Corporate Office Network & Cybersecurity Build', 'Network & Cybersecurity', 'corporate', '["structured-cabling","lan-wan","network-security","firewall-endpoint-protection","access-control-systems"]'::jsonb, 'Lagos (Victoria Island)', '6-floor HQ · 300+ users', 'A growing professional-services firm needed a secure, segmented network for a new headquarters.', '["Structured cabling and managed switching across 6 floors","Segmented networks for staff, guests and building systems","Next-gen firewall and endpoint protection deployed","Access control with audit trail across the building"]'::jsonb, 'modern corporate office server room and network racks', '2025', true),
('p-003', 'Hotel Fire Safety & Guest Access Integration', 'Fire Safety & Access', 'hospitality', '["fire-alarm-systems","access-control-systems","intercom-systems","cctv-installation"]'::jsonb, 'Lekki, Lagos', 'Boutique hotel · 60 rooms', 'A boutique hotel required compliant fire detection and guest access control.', '["Addressable fire alarm system with full coverage","Door access integrated with fire-alarm evacuation release","Discreet surveillance of public and service areas","Video intercom with remote gate unlock"]'::jsonb, 'boutique hotel lobby fire safety and access control systems', '2025', true),
('p-004', 'Warehouse Perimeter & Inventory Protection', 'Perimeter & Surveillance', 'warehouse', '["perimeter-intrusion","cctv-installation","access-control-systems","burglar-alarm-systems"]'::jsonb, 'Agbara, Ogun', 'Large logistics warehouse', 'A logistics operator was losing inventory to perimeter breaches.', '["Perimeter beam detection along the full boundary","CCTV triggered recording on perimeter breach","Access control for staff and vehicles","Integrated alarm and alerting"]'::jsonb, 'warehouse perimeter security infrared beam cameras at night', '2025', false),
('p-005', 'School Campus Wi-Fi & Surveillance', 'Networking & Surveillance', 'education', '["wifi-installation","cctv-installation","lan-wan","access-control-systems"]'::jsonb, 'Ibadan, Oyo', 'Campus · multiple buildings', 'A school needed campus-wide Wi-Fi for staff and students, plus surveillance to improve safety.', '["Heat-mapped enterprise Wi-Fi across the campus","Segmented networks for staff, students and guests","CCTV coverage of key campus areas","Access control for labs and offices"]'::jsonb, 'school campus wifi access points and security cameras', '2025', false),
('p-006', 'Hospital Server Room & Resilient IT', 'IT Infrastructure', 'healthcare', '["server-data-centre","network-security","computer-it-support","fire-detection-safety"]'::jsonb, 'Surulere, Lagos', 'Hospital data centre', 'A hospital needed resilient IT infrastructure for patient systems and data.', '["Server room fit-out with racks, UPS and cooling","Backup and recovery strategy with tested restore","Network hardening and segmentation","Ongoing managed IT support"]'::jsonb, 'hospital server room with racks ups and cooling', '2025', false),
('p-007', 'Construction Site Mobile Surveillance', 'Surveillance', 'construction', '["cctv-installation","video-monitoring","perimeter-intrusion","burglar-alarm-systems"]'::jsonb, 'Eko Atlantic, Lagos', 'Live construction site', 'A developer was losing materials to night-time theft on a live construction site.', '["Mobile surveillance adaptable to site changes","Perimeter detection with remote alerts","No fixed infrastructure required","Reduced material losses"]'::jsonb, 'construction site mobile surveillance cameras at night', '2025', false),
('p-008', 'Estate Access Control & Smart Security', 'Access & Surveillance', 'residential', '["access-control-systems","cctv-installation","intercom-systems","burglar-alarm-systems","wifi-installation"]'::jsonb, 'Lekki Phase 1, Lagos', 'Gated residential estate', 'A gated estate wanted controlled access for residents, staff and visitors.', '["Gate access control with video intercoms","Resident and visitor credential management","CCTV coverage of entry and common areas","Estate-wide Wi-Fi for management"]'::jsonb, 'gated residential estate gate access control and cameras', '2025', false),
('p-009', 'Manufacturing Plant Fire Safety & Network', 'Fire Safety & Network', 'industrial', '["fire-detection-safety","fire-alarm-systems","structured-cabling","cctv-installation"]'::jsonb, 'Ikeja, Lagos', 'Manufacturing facility', 'A manufacturing plant needed compliant fire safety and a reliable network.', '["Comprehensive fire detection and safety systems","Structured cabling across the production floor","Surveillance of operational and asset areas","Compliance-ready documentation"]'::jsonb, 'manufacturing plant fire safety and network infrastructure', '2025', false)
ON CONFLICT ("id") DO UPDATE SET "title" = EXCLUDED."title", "category" = EXCLUDED."category", "industry" = EXCLUDED."industry", "services" = EXCLUDED."services", "location" = EXCLUDED."location", "scope" = EXCLUDED."scope", "description" = EXCLUDED."description", "highlights" = EXCLUDED."highlights", "imageQuery" = EXCLUDED."imageQuery", "year" = EXCLUDED."year", "featured" = EXCLUDED."featured", "updatedAt" = CURRENT_TIMESTAMP;

-- ═══════════════════════════════════════════════════════════
--  SEED: FAQs (16)
-- ═══════════════════════════════════════════════════════════
INSERT INTO "Faq" ("id", "category", "question", "answer", "sortOrder") VALUES
('f1', 'Services & Scope', 'What services does Allison Global offer?', 'We cover six core domains: Network & Connectivity, Cybersecurity, Surveillance & Monitoring, Access Control & Automation, Alarm & Fire Safety, and IT Infrastructure & Support. Each spans multiple specialist services — from structured cabling to managed IT — so your network, security and IT systems are handled by one engineering-led team.', 1),
('f2', 'Services & Scope', 'Do you work on both homes and businesses?', 'Yes. We serve homes and residential estates, offices, businesses, institutions and industries. The scale differs, but the engineering approach is the same — assess, design, install, integrate and support.', 2),
('f3', 'Services & Scope', 'Can you integrate CCTV, access control, alarms and networking?', 'Absolutely — integration is a core strength. Many security issues come from systems that do not talk to each other. We design CCTV, access control, alarms and networking to work as one platform.', 3),
('f4', 'Services & Scope', 'Do you supply the equipment, or only install?', 'We do both. We assess, design, supply, install, integrate and maintain. Equipment is sourced through proper channels as genuine, warrantied product.', 4),
('f5', 'Process & Engagement', 'How does a project typically start?', 'It starts with a consultation and site assessment. A senior engineer visits your site, understands your needs and risks, and documents what is actually required. You then receive a clear proposal with scope, equipment and pricing before any work begins.', 1),
('f6', 'Process & Engagement', 'Do you provide documentation after installation?', 'Yes — every project is handed over with as-built documentation, system diagrams, credentials, manuals and a maintenance schedule.', 2),
('f7', 'Process & Engagement', 'Can you work with equipment we already have?', 'In many cases, yes. During the assessment we review your existing infrastructure and advise what can be retained, upgraded or replaced.', 3),
('f8', 'Process & Engagement', 'How long does a typical installation take?', 'It depends on scope. A small CCTV or access control install can take a day or two; a full office network or multi-site rollout takes longer and is phased to minimise disruption. You will get a clear timeline in your proposal.', 4),
('f9', 'Support & Maintenance', 'Do you offer ongoing support and maintenance?', 'Yes — through our Managed Services & Technical Support plans. We provide preventive maintenance, monitoring, priority support and ongoing improvement under a predictable agreement.', 1),
('f10', 'Support & Maintenance', 'How quickly can you respond to support requests?', 'Managed-support clients have defined response-time SLAs, with a target priority response of under 4 hours for critical issues. For ad-hoc support, we respond as quickly as our engineering schedule allows.', 2),
('f11', 'Support & Maintenance', 'Is there a warranty on your installations?', 'Installations are covered by a workmanship warranty so defects in our installation work are put right. Equipment itself carries the manufacturer warranty, which we help you manage.', 3),
('f12', 'Security & Data', 'How do you keep our network and data secure?', 'Security is built in, not bolted on. We design segmented networks, deploy next-gen firewalls and endpoint protection, follow least-privilege access, and document credentials securely.', 1),
('f13', 'Security & Data', 'Can you help us with cybersecurity if we have no in-house team?', 'Yes — that is exactly what our Cybersecurity services and Managed Services are designed for. We act as your security partner.', 2),
('f14', 'Security & Data', 'Do you offer security assessments and audits?', 'Yes. Our Security Assessment & Consultation service evaluates your network, systems and physical security against real threats and produces a prioritised, jargon-free remediation roadmap.', 3),
('f15', 'Location & Coverage', 'Where are you based, and which areas do you cover?', 'We are headquartered in Lagos, Nigeria, and deliver projects nationwide with rapid-response support across major Nigerian cities.', 1),
('f16', 'Location & Coverage', 'Can you support multiple sites across different locations?', 'Yes. We frequently deploy unified surveillance, networking and security across multiple branches or sites, with centralised management and monitoring.', 2)
ON CONFLICT ("id") DO UPDATE SET "category" = EXCLUDED."category", "question" = EXCLUDED."question", "answer" = EXCLUDED."answer", "sortOrder" = EXCLUDED."sortOrder", "updatedAt" = CURRENT_TIMESTAMP;

-- ═══════════════════════════════════════════════════════════
--  SEED: BLOG POSTS (6)
-- ═══════════════════════════════════════════════════════════
INSERT INTO "BlogPost" ("slug", "title", "excerpt", "category", "readTime", "date", "author", "authorRole", "imageQuery", "content", "tags", "featured") VALUES
('how-to-choose-cctv-system-nigeria', 'How to Choose the Right CCTV System for Your Business in Nigeria', 'Resolution, coverage, storage and night capability matter far more than camera count.', 'Surveillance', '7 min read', '2025-10-12', 'Agu Chisom Alvin', 'Founder & CEO, Allison Global', 'cctv security camera installation on building exterior', '[{"body":"Most businesses buy CCTV the same way: a few cameras, a recorder, and hope. Here is how to specify a CCTV system that delivers usable footage when it matters."},{"heading":"Start with what you need to see","body":"Before discussing camera models, define your risk areas: entrances, exits, point-of-sale counters, stockrooms, loading bays, car parks and cash-handling points."},{"heading":"Resolution and lensing matter more than camera count","body":"A single 4K camera with the right lens can outperform four cheap ones."},{"heading":"Do not forget night capability","body":"Most incidents happen after dark. Cameras need either strong infrared or true low-light sensors."},{"heading":"Size storage to your retention needs","body":"Footage is only useful if it is still there when you discover an incident."},{"body":"A well-designed CCTV system is an investment that pays for itself the first time it deters a loss or provides the evidence you need."}]'::jsonb, '["CCTV","Surveillance","Security"]'::jsonb, true),
('cybersecurity-basics-nigerian-smes', 'Cybersecurity Basics Every Nigerian SME Should Get Right First', 'Before you invest in advanced tools, get these fundamentals right.', 'Cybersecurity', '8 min read', '2025-10-28', 'Allison Global Team', 'Allison Global Insights', 'cybersecurity firewall network protection concept', '[{"body":"Small and medium businesses are now a primary target for cybercriminals."},{"heading":"1. A real firewall, not a consumer router","body":"Your internet router is not a security device."},{"heading":"2. Endpoint protection that detects behaviour","body":"Free antivirus matches against known signatures."},{"heading":"3. Segment your network","body":"A flat network means one infected device can reach everything."},{"heading":"4. Backups that survive an attack","body":"Follow the 3-2-1 rule."},{"heading":"5. Multi-factor authentication everywhere","body":"Stolen passwords still drive most breaches."},{"heading":"6. Patching and updates","body":"Known vulnerabilities in unpatched software are an open door."},{"body":"Get these six right and you have closed the door on the majority of attacks."}]'::jsonb, '["Cybersecurity","Network Security","SME"]'::jsonb, true),
('structured-cabling-future-proofing', 'Why Structured Cabling Is the Investment You Will Thank Yourself For', 'The cabling behind your network, CCTV and access systems outlasts almost everything else.', 'Networking', '6 min read', '2025-10-10', 'Agu Chisom Alvin', 'Founder & CEO, Allison Global', 'structured cabling network rack tidy patch panel', '[{"body":"Structured cabling is invisible — until something breaks."},{"heading":"Everything runs on the cable","body":"Your network, phones, CCTV, access control, Wi-Fi and IT systems all depend on the same cabling foundation."},{"heading":"Standards, testing and documentation","body":"Proper structured cabling follows TIA/EIA standards."},{"heading":"Future-proofing is cheap insurance","body":"Installing higher-specification cable costs marginally more during installation."},{"heading":"Tidy racks save money","body":"A well-dressed, labelled rack makes troubleshooting fast."},{"body":"Cabling is the foundation everything else stands on."}]'::jsonb, '["Networking","Cabling","Infrastructure"]'::jsonb, false),
('access-control-vs-traditional-keys', 'Access Control vs Traditional Keys: The Business Case', 'Keys get lost, copied and never returned. Access control gives you control and audit trails.', 'Access Control', '6 min read', '2025-09-22', 'Allison Global Team', 'Allison Global Insights', 'access control card reader door entry system', '[{"body":"Keys have served buildings for centuries, but for modern businesses they are a liability."},{"heading":"Control who goes where, and when","body":"Access control lets you define exactly which doors each person can open."},{"heading":"Audit trails change investigations","body":"When something goes wrong, access control tells you who was where."},{"heading":"Instant revocation, no rekeying","body":"When staff leave, you revoke access in seconds."},{"body":"Access control is not just about replacing keys — it is about gaining control, visibility and integration."}]'::jsonb, '["Access Control","Security"]'::jsonb, false),
('fire-safety-compliance-nigeria', 'Fire Safety Compliance: What Nigerian Businesses Should Know', 'Fire safety is not just good practice — it is a regulatory and insurance matter.', 'Fire Safety', '7 min read', '2025-09-05', 'Allison Global Team', 'Allison Global Insights', 'fire alarm smoke detector and sounder on ceiling', '[{"body":"Fire safety is a life-safety matter — but it is also a regulatory and insurance one."},{"heading":"Detection designed for the space","body":"Different spaces need different detection."},{"heading":"Audible and visual alerting","body":"Everyone on the premises must be alerted."},{"heading":"Addressable systems for larger sites","body":"For larger premises, addressable fire alarm systems identify exactly which detector triggered."},{"heading":"Integration for safe evacuation","body":"Fire alarms should integrate with access control to release doors."},{"body":"Fire safety is one area where cutting corners costs lives and money."}]'::jsonb, '["Fire Safety","Compliance"]'::jsonb, false),
('managed-services-vs-break-fix', 'Managed IT Services vs Break-Fix: The Real Cost Comparison', 'Break-fix feels cheaper — until you count the downtime.', 'IT Support', '6 min read', '2025-08-19', 'Allison Global Team', 'Allison Global Insights', 'IT support engineer monitoring systems dashboard', '[{"body":"Many businesses still operate on a break-fix model."},{"heading":"Break-fix means downtime you pay for","body":"Every hour a system is down is lost productivity."},{"heading":"Managed services catch issues early","body":"With monitoring and preventive maintenance, managed services catch failures before they become outages."},{"heading":"Predictable costs, predictable support","body":"Managed services give you a predictable monthly cost."},{"body":"For most businesses, managed services cost less than the downtime, surprises and risk of break-fix."}]'::jsonb, '["Managed Services","IT Support"]'::jsonb, false)
ON CONFLICT ("slug") DO UPDATE SET "title" = EXCLUDED."title", "excerpt" = EXCLUDED."excerpt", "category" = EXCLUDED."category", "readTime" = EXCLUDED."readTime", "date" = EXCLUDED."date", "author" = EXCLUDED."author", "authorRole" = EXCLUDED."authorRole", "imageQuery" = EXCLUDED."imageQuery", "content" = EXCLUDED."content", "tags" = EXCLUDED."tags", "featured" = EXCLUDED."featured", "updatedAt" = CURRENT_TIMESTAMP;

-- ═══════════════════════════════════════════════════════════
--  SEED: SERVICES (26) — uses DO $$ to resolve category FKs
-- ═══════════════════════════════════════════════════════════
DO $$
DECLARE
  cat_network TEXT; cat_cyber TEXT; cat_surv TEXT; cat_access TEXT; cat_alarm TEXT; cat_infra TEXT;
BEGIN
  SELECT id INTO cat_network FROM "Category" WHERE slug = 'network-connectivity';
  SELECT id INTO cat_cyber FROM "Category" WHERE slug = 'cybersecurity';
  SELECT id INTO cat_surv FROM "Category" WHERE slug = 'surveillance-monitoring';
  SELECT id INTO cat_access FROM "Category" WHERE slug = 'access-control';
  SELECT id INTO cat_alarm FROM "Category" WHERE slug = 'alarm-fire-safety';
  SELECT id INTO cat_infra FROM "Category" WHERE slug = 'it-infrastructure';

  INSERT INTO "Service" ("slug", "name", "categoryId", "tagline", "shortDescription", "overview", "problem", "solution", "deliverables", "benefits", "tech", "relatedServices", "relatedIndustries", "featured", "iconName", "sortOrder") VALUES
  ('structured-cabling', 'Structured Cabling', cat_network, 'A cabling foundation engineered to carry your business for decades', 'Standards-compliant copper, fibre and rack cabling with proper labelling, testing and certification.', 'We design and install Cat6/Cat6A copper and fibre-optic cabling to TIA/EIA standards.', '["Slow intermittent connections from poorly terminated cabling","No documentation so every change is a guessing game","Cabling that fails under high bandwidth","Messy racks that make troubleshooting painful"]'::jsonb, 'We engineer a structured cabling system around your building, bandwidth and growth plans.', '[{"title":"Site survey & cable design","description":"Cable routes, outlet counts, rack locations and material take-off."},{"title":"Copper & fibre installation","description":"Cat6/Cat6A and OS2/OM4 fibre pulled, terminated and dressed to standard."},{"title":"Patch panels & racks","description":"Wall and floor racks, patch panels, cable managers and tidy, labelled patching."},{"title":"Certification testing","description":"Fluke-class testers validate every link."},{"title":"As-built documentation","description":"Outlet schedules, rack diagrams and cable labels."}]'::jsonb, '["Reliable gigabit and multi-gig performance","Clean, documented infrastructure","Fewer outages and faster fault-finding","Future-proofed headroom"]'::jsonb, '["Cat6/Cat6A","Single-mode & multimode fibre","LSZH cabling","Cable certification testers","Racks & cable management"]'::jsonb, '["lan-wan","network-installation","wifi-installation","cctv-installation","access-control-systems"]'::jsonb, '["corporate","education","healthcare","industrial","warehouse"]'::jsonb, true, 'Cable', 1),
  ('lan-wan', 'LAN / WAN Solutions', cat_network, 'Switching, routing and segmentation done right', 'Layer 2/3 switching, VLANs, routing and inter-site connectivity designed for performance and segmentation.', 'We design and deploy LAN and WAN infrastructure with managed switching, VLAN segmentation, routing and inter-site links.', '["Congested flat networks where CCTV competes with data","Intermittent dropouts from consumer switches","No segmentation between guest staff and device networks","Multi-site connectivity that is slow or insecure"]'::jsonb, 'We architect your LAN/WAN with enterprise switching, VLAN design, routing and secure inter-site links.', '[{"title":"Network architecture","description":"Topology, VLAN plan, IP scheme and segmentation strategy."},{"title":"Managed switching","description":"Layer 2/3 switches configured with VLANs, QoS and link aggregation."},{"title":"Routing & WAN","description":"Router configuration, inter-site VPN and WAN aggregation."},{"title":"Segmentation","description":"Separate networks for data, voice, surveillance, guests and IoT."},{"title":"Documentation & handover","description":"Configuration backup, IP plan and operational runbook."}]'::jsonb, '["Clean separation of traffic","Reliable connectivity that scales","Better application performance","Secure multi-site connectivity"]'::jsonb, '["Managed L2/L3 switches","VLANs & 802.1Q","Site-to-site VPN","QoS","Link aggregation"]'::jsonb, '["network-installation","structured-cabling","network-security","firewall-endpoint-protection","wifi-installation"]'::jsonb, '["corporate","education","healthcare","finance","industrial"]'::jsonb, false, 'Router', 2),
  ('wifi-installation', 'Wi-Fi Installation & Optimization', cat_network, 'Coverage you can actually rely on, in every corner', 'Heat-mapped wireless deployments and optimisation for offices, hotels, campuses and large homes.', 'We design wireless networks using proper site surveys and heat maps, deploy enterprise access points with seamless roaming, and tune them for capacity, coverage and speed.', '["Dead spots and weak signal in key areas","Wi-Fi that slows when many users connect","Guest Wi-Fi sharing the same network as staff","Roaming that drops calls and sessions"]'::jsonb, 'We survey your environment, design access-point placement for true coverage, and configure enterprise Wi-Fi with seamless roaming, band steering and guest isolation.', '[{"title":"Wireless site survey","description":"Heat-mapped coverage planning based on walls, floors and layout."},{"title":"Access point deployment","description":"Enterprise APs placed and mounted for optimal coverage and capacity."},{"title":"SSID & security design","description":"Separate networks for staff, guests and devices with WPA2/3 security."},{"title":"Roaming & optimisation","description":"Seamless 802.11r/k/v roaming, band steering and channel tuning."},{"title":"Performance validation","description":"Post-installation testing confirming coverage and throughput."}]'::jsonb, '["Reliable coverage everywhere it matters","Higher capacity for many simultaneous users","Secure guest access isolated from business data","Seamless roaming without dropped connections"]'::jsonb, '["Wi-Fi 6 / 6E access points","Controller & cloud-managed Wi-Fi","Mesh & roaming protocols","WPA3","Heat-map survey tools"]'::jsonb, '["network-installation","lan-wan","network-security","structured-cabling","smart-building-solutions"]'::jsonb, '["hospitality","education","corporate","residential","retail"]'::jsonb, true, 'Wifi', 3),
  ('network-installation', 'Network Installation & Infrastructure', cat_network, 'End-to-end network build, from rack to endpoint', 'Turnkey network installation — design, supply, configuration, commissioning and handover.', 'We handle the full installation — supply of enterprise equipment, rack build, configuration, commissioning and handover.', '["Equipment bought but never properly configured","Installations with no testing or documentation","Vendors who disappear after deployment","Networks that work on day one and degrade from day two"]'::jsonb, 'We install your network end-to-end — supply, configure, test, commission and document.', '[{"title":"Equipment supply","description":"Genuine enterprise equipment sourced and supplied with warranty."},{"title":"Rack build & cabling","description":"Clean rack assembly with proper cable management."},{"title":"Configuration","description":"Switches, routers, APs and security configured to design."},{"title":"Commissioning & testing","description":"End-to-end validation before handover."},{"title":"Handover & documentation","description":"As-built docs, credentials and operational runbook."}]'::jsonb, '["One accountable partner","Stable tested network from day one","Documented and supportable","Genuine warrantied equipment"]'::jsonb, '["Enterprise switches & routers","Racks & UPS","Network configuration management","Documentation tooling"]'::jsonb, '["structured-cabling","lan-wan","wifi-installation","network-security","network-maintenance"]'::jsonb, '["corporate","education","healthcare","industrial","warehouse"]'::jsonb, false, 'Network', 4),
  ('network-maintenance', 'Network Maintenance & Support', cat_network, 'Keep the backbone healthy, not just installed', 'Preventive maintenance, monitoring and rapid-response support for your network infrastructure.', 'Our maintenance and support keeps your network healthy with scheduled health checks, monitoring, firmware management and priority response.', '["Slow deterioration nobody notices","Outdated firmware with known vulnerabilities","No monitoring so outages are discovered by users","Slow vendor response when the network goes down"]'::jsonb, 'We keep your network under maintenance — proactive monitoring, scheduled servicing, firmware updates and priority response.', '[{"title":"Health checks","description":"Scheduled audits of switching, routing and wireless performance."},{"title":"Monitoring","description":"Proactive monitoring that flags issues before users do."},{"title":"Firmware management","description":"Planned updates and security patching."},{"title":"Priority response","description":"Defined SLA response times for support clients."},{"title":"Change management","description":"Configuration backups and controlled change."}]'::jsonb, '["Fewer surprise outages","Security patches applied on schedule","Faster resolution when issues occur","Predictable support costs"]'::jsonb, '["Network monitoring (SNMP)","Configuration backup","Firmware management","Remote support"]'::jsonb, '["network-installation","managed-services","network-security","computer-it-support"]'::jsonb, '["corporate","education","healthcare","finance","industrial"]'::jsonb, false, 'LifeBuoy', 5),
  ('network-security', 'Network Security', cat_cyber, 'Defend the perimeter and everything inside it', 'Layered network security — firewalls, segmentation, secure access and policy — engineered to your risk profile.', 'We design layered defences — perimeter firewalls, internal segmentation, secure remote access, policy and monitoring — so threats are blocked, contained and visible.', '["A single firewall protecting a flat exposed network","No visibility into what enters or leaves","Insecure remote access opening doors to attackers","Guest and IoT devices sharing privileged network space"]'::jsonb, 'We engineer layered network security around your actual risk.', '[{"title":"Security architecture","description":"Defence-in-depth design tailored to your risk and compliance needs."},{"title":"Firewall & segmentation","description":"Next-gen firewalling and network segmentation policies."},{"title":"Secure remote access","description":"VPN and zero-trust access for staff and partners."},{"title":"Policy & controls","description":"Access policies, URL filtering and application control."},{"title":"Monitoring & alerts","description":"Logging and alerting on suspicious activity."}]'::jsonb, '["Reduced attack surface","Visibility into network threats","Secure remote and partner access","Stronger posture for compliance"]'::jsonb, '["Next-gen firewalls","Network segmentation","VPN / zero-trust access","URL & app filtering","SIEM logging"]'::jsonb, '["firewall-endpoint-protection","intrusion-detection","security-assessment","lan-wan","managed-services"]'::jsonb, '["finance","corporate","government","healthcare","education"]'::jsonb, true, 'ShieldCheck', 6),
  ('firewall-endpoint-protection', 'Firewall & Endpoint Protection', cat_cyber, 'Guard the gate and every device behind it', 'Next-gen firewalls and endpoint protection (EDR/AV) to block malware, ransomware and breaches.', 'We deploy and manage both — next-gen firewalls with threat prevention, plus modern endpoint detection and response.', '["Consumer antivirus that misses modern threats","A firewall with no threat prevention","Ransomware reaching endpoints unchecked","Unmanaged devices spreading infection"]'::jsonb, 'We deploy next-gen firewalls with threat prevention and modern endpoint protection across your devices.', '[{"title":"Next-gen firewalling","description":"Firewall with IDS/IPS, anti-malware, web filtering and application control."},{"title":"Endpoint protection","description":"EDR/antivirus deployed across workstations and servers."},{"title":"Central management","description":"Single console for policy, alerts and remediation."},{"title":"Ransomware defence","description":"Behavioural detection and rollback where supported."},{"title":"Ongoing management","description":"Policy tuning, alerts and reporting under support plans."}]'::jsonb, '["Blocked malware ransomware and phishing","Visibility and control across endpoints","Faster detection and response","Reduced downtime and data-loss risk"]'::jsonb, '["Fortinet / SonicWall","Bitdefender EDR","Central management consoles","Threat intelligence"]'::jsonb, '["network-security","intrusion-detection","security-assessment","server-data-centre","managed-services"]'::jsonb, '["finance","corporate","healthcare","government","smb"]'::jsonb, false, 'Lock', 7),
  ('intrusion-detection', 'Intrusion Detection & Prevention', cat_cyber, 'Spot the threats that get past the front door', 'IDS/IPS and monitoring that detects and blocks intrusion attempts on your network.', 'We deploy and tune IDS/IPS so you are not just defended, you are aware.', '["Breaches that go unnoticed for weeks","Firewalls that block known bad traffic but miss novel attacks","No alerting when attackers probe the network","Compliance requirements for continuous monitoring"]'::jsonb, 'We deploy IDS/IPS with tuned signatures and behaviour monitoring, integrated with your firewall and logging.', '[{"title":"IDS/IPS deployment","description":"Network-based intrusion detection and prevention, tuned to your environment."},{"title":"Signature & behaviour rules","description":"Curated rulesets with false-positive tuning."},{"title":"Alerting & escalation","description":"Alerts routed to the right people with clear severity."},{"title":"Logging integration","description":"Centralised logging for investigation and compliance."},{"title":"Regular tuning","description":"Ongoing rule updates under support plans."}]'::jsonb, '["Earlier detection of attacks","Automated blocking of known threats","Investigation-ready logs","Stronger compliance posture"]'::jsonb, '["IDS/IPS engines","Next-gen firewall threat prevention","SIEM / log aggregation","Threat intelligence feeds"]'::jsonb, '["network-security","firewall-endpoint-protection","security-assessment","managed-services"]'::jsonb, '["finance","government","healthcare","corporate"]'::jsonb, false, 'ScanEye', 8),
  ('security-assessment', 'Security Assessment & Consultation', cat_cyber, 'Know your risks before attackers do', 'Practical security assessments, audits and roadmap planning — translated into clear, prioritised action.', 'Our security assessments evaluate your network, systems, surveillance and physical security against real threats.', '["Uncertainty about where the real risks are","Budget spent on tools without a clear strategy","Compliance demands you are not sure you meet","No independent view of your security posture"]'::jsonb, 'We assess your environment, document risks against likelihood and impact, and produce a prioritised, practical remediation roadmap.', '[{"title":"Risk assessment","description":"Identification and rating of threats across network, systems and physical security."},{"title":"Vulnerability review","description":"Scanning and review of exposed services and weak configurations."},{"title":"Gap analysis","description":"Where you stand versus best practice and any regulatory needs."},{"title":"Remediation roadmap","description":"Prioritised, cost-aware plan of what to fix first."},{"title":"Executive briefing","description":"Clear, plain-language summary for decision-makers."}]'::jsonb, '["Clarity on real risks and priorities","Defensible, documented security posture","Confident, budget-aware decision-making","Foundation for a proper security programme"]'::jsonb, '["Vulnerability scanners","Configuration review","Risk frameworks","Reporting"]'::jsonb, '["network-security","firewall-endpoint-protection","intrusion-detection","managed-services"]'::jsonb, '["finance","corporate","government","healthcare","smb"]'::jsonb, false, 'ShieldAlert', 9),
  ('cctv-installation', 'CCTV Installation', cat_surv, 'Coverage engineered so nothing is missed', 'Professional CCTV design and installation with the right cameras in the right places — and reliable playback.', 'We design surveillance around what you need to see, deploy quality cameras with proper lensing and lighting, and configure reliable storage and remote access.', '["Cameras that capture nothing useful","Blind spots at entrances, loading bays and key assets","Footage too grainy to be useful","Systems with no remote viewing or unreliable playback"]'::jsonb, 'We design CCTV around your risk areas, deploy quality cameras with proper lensing and night capability, and configure reliable storage and remote access.', '[{"title":"Coverage design","description":"Camera placement plan mapped to your risk areas and sightlines."},{"title":"Camera deployment","description":"Right cameras for each scene — resolution, lens, IR and WDR tuned."},{"title":"Storage & retention","description":"NVR/storage sized for your retention needs."},{"title":"Remote viewing","description":"Secure mobile and web access to live and recorded footage."},{"title":"Commissioning & handover","description":"Angle tuning, focus checks and user training."}]'::jsonb, '["Useable footage of the areas that matter","Deterrent and evidence when incidents occur","Reliable remote monitoring","Foundation for integration with access and alarms"]'::jsonb, '["Hikvision / Dahua cameras","4K & varifocal cameras","IR & low-light","NVR storage","Mobile/web viewing"]'::jsonb, '["ip-camera-systems","video-monitoring","nvr-dvr-solutions","structured-cabling","access-control-systems","perimeter-intrusion"]'::jsonb, '["retail","warehouse","corporate","residential","industrial","construction"]'::jsonb, true, 'Camera', 10),
  ('ip-camera-systems', 'IP Camera Systems', cat_surv, 'Modern IP video with the clarity and intelligence you need', 'Network-based IP camera systems with high resolution, smart analytics and scalable storage.', 'We design IP video systems that deliver clear footage, intelligent detection, and storage that scales with your camera count.', '["Older analogue systems with poor image quality","Need for smart features like motion alerts and analytics","Scaling beyond what the existing system can handle","Desire for remote, multi-site viewing on one platform"]'::jsonb, 'We deploy IP camera systems with high-resolution cameras, smart analytics and scalable NVR/storage.', '[{"title":"IP camera selection","description":"Resolution, lensing and analytics matched to each scene."},{"title":"Smart analytics","description":"Motion, line-crossing, intrusion and people/vehicle detection."},{"title":"Scalable storage","description":"NVR with RAID and retention sized to camera count."},{"title":"Multi-site viewing","description":"Centralised platform for one or many locations."},{"title":"Network integration","description":"Proper VLAN isolation for clean video traffic."}]'::jsonb, '["Sharper more usable footage","Smarter alerts instead of constant recording review","Easier scaling as needs grow","Unified viewing across sites"]'::jsonb, '["IP cameras (4K/2K)","Edge analytics","PoE switching","NVR with RAID","VMS platforms"]'::jsonb, '["cctv-installation","video-monitoring","nvr-dvr-solutions","network-security","lan-wan"]'::jsonb, '["retail","warehouse","corporate","industrial","education"]'::jsonb, false, 'Video', 11),
  ('video-monitoring', 'Video Monitoring & Remote Viewing', cat_surv, 'Eyes on your premises, even when you are away', 'Remote monitoring, live viewing and event-based alerting across single or multiple sites.', 'We set up remote monitoring so you (or our team) can view live footage, receive event-based alerts, and review recordings from anywhere.', '["Cameras installed but nobody watching","No alerts when something actually happens","Cannot view footage when off-site","Multiple sites with no unified view"]'::jsonb, 'We configure remote monitoring with live viewing, event-based alerts and a unified multi-site platform.', '[{"title":"Remote viewing setup","description":"Secure mobile and web access to live and recorded footage."},{"title":"Event alerts","description":"Push/email alerts for motion, line-crossing and intrusion events."},{"title":"Multi-site platform","description":"Unified dashboard across all your locations."},{"title":"Monitoring integration","description":"Optional integration with access control and alarms."},{"title":"User management","description":"Role-based access for staff and security teams."}]'::jsonb, '["Real-time awareness across sites","Faster response to incidents","Reduced need for constant manual monitoring","Centralised oversight of security"]'::jsonb, '["VMS / mobile apps","Push & email alerting","Cloud / on-prem platforms","Role-based access"]'::jsonb, '["cctv-installation","ip-camera-systems","nvr-dvr-solutions","access-control-systems","burglar-alarm-systems"]'::jsonb, '["retail","warehouse","hospitality","corporate","construction"]'::jsonb, false, 'MonitorPlay', 12),
  ('nvr-dvr-solutions', 'NVR / DVR & Storage Solutions', cat_surv, 'Reliable recording that keeps your footage when it counts', 'Network and digital video recorders with RAID storage, retention planning and redundancy.', 'We deploy NVR and DVR solutions with properly sized storage, RAID redundancy, retention planning and reliable recording schedules.', '["Footage lost or overwritten before an incident is noticed","Single-drive recorders with no redundancy","Storage too small for the camera count","Unreliable recording that misses the moment"]'::jsonb, 'We size and deploy NVR/DVR storage with redundancy and retention planning matched to your cameras and needs.', '[{"title":"Storage sizing","description":"Capacity calculated from camera count, resolution, retention and activity."},{"title":"RAID & redundancy","description":"Disk redundancy so a failed drive does not lose footage."},{"title":"Retention planning","description":"Recording schedules and retention aligned to requirements."},{"title":"Backup options","description":"Off-site or cloud backup for critical footage."},{"title":"Health monitoring","description":"Disk health monitoring and alerts under support plans."}]'::jsonb, '["Footage available when you need it — days later","Protection against drive failure","Right-sized storage","Confident retention for compliance"]'::jsonb, '["NVR / DVR","RAID storage","Surveillance-grade disks","Cloud backup","Retention scheduling"]'::jsonb, '["cctv-installation","ip-camera-systems","video-monitoring","network-installation"]'::jsonb, '["retail","warehouse","finance","corporate","hospitality"]'::jsonb, false, 'HardDrive', 13),
  ('access-control-systems', 'Access Control Systems', cat_access, 'Decide who goes where, and when', 'Card, fob and app-based access control with audit trails, schedules and integration.', 'We design and deploy access control that scales from a single door to a full building or campus.', '["Lost or copied keys compromising security","No record of who entered and when","Difficulty revoking access for former staff","Different access needs for different roles and times"]'::jsonb, 'We deploy card/fob/app access control with role-based permissions, schedules and full audit trails.', '[{"title":"Access design","description":"Door-by-door permissions, roles and schedules."},{"title":"Reader & controller deployment","description":"Readers, controllers and locking hardware installed."},{"title":"Credential management","description":"Card/fob/app enrolment and easy revocation."},{"title":"Audit trails","description":"Full entry/exit logging and reporting."},{"title":"Integration","description":"Link with CCTV, alarms and time attendance where needed."}]'::jsonb, '["Control and visibility over who enters","Instant revocation — no rekeying","Audit trail for investigations and compliance","Flexible, role-based access"]'::jsonb, '["Card/fob/mobile readers","Access controllers","Management software","Electric locks & strikes"]'::jsonb, '["biometric-systems","door-access-systems","intercom-systems","cctv-installation","burglar-alarm-systems"]'::jsonb, '["corporate","finance","government","healthcare","education","warehouse"]'::jsonb, true, 'KeyRound', 14),
  ('biometric-systems', 'Biometric Systems', cat_access, 'Identity you cannot lose or share', 'Fingerprint and facial recognition for access control and time attendance.', 'We deploy fingerprint and facial-recognition systems for access control and time & attendance.', '["Shared or borrowed cards undermining access control","Buddy-punching inflating attendance records","Need for higher-assurance identity at sensitive doors","Manual attendance processes prone to error"]'::jsonb, 'We deploy biometric readers for access control and time attendance.', '[{"title":"Biometric reader deployment","description":"Fingerprint and/or facial recognition at chosen doors."},{"title":"Enrolment & management","description":"User enrolment and ongoing management."},{"title":"Time & attendance","description":"Attendance records exportable for payroll."},{"title":"Access integration","description":"Biometric integrated with your access control platform."},{"title":"Reporting","description":"Attendance and access reports on demand."}]'::jsonb, '["Higher-assurance identity verification","Eliminates card sharing and buddy-punching","Accurate attendance for payroll","Strong audit trail"]'::jsonb, '["Fingerprint readers","Facial recognition","Time & attendance software","ZKTeco platforms"]'::jsonb, '["access-control-systems","door-access-systems","intercom-systems","smart-building-solutions"]'::jsonb, '["corporate","finance","government","education","industrial"]'::jsonb, false, 'Fingerprint', 15),
  ('door-access-systems', 'Door Access Systems', cat_access, 'Secure, reliable door hardware that just works', 'Electric locks, strikes, magnetic locks and turnstiles — installed and integrated for reliable operation.', 'We supply and install electric strikes, magnetic locks, automatic doors and turnstiles — integrated with your access control.', '["Cheap locking hardware that fails or jams","Doors that do not reliably lock after entry","Hardware not integrated with access control","Bottlenecks at busy entrances"]'::jsonb, 'We install quality electric locking hardware — strikes, maglocks, automatic doors and turnstiles — integrated with your access platform.', '[{"title":"Hardware selection","description":"Right locking hardware for each door type and traffic."},{"title":"Installation","description":"Professional mounting, wiring and safety compliance."},{"title":"Access integration","description":"Hardware wired to controllers and fire-alarm safety release."},{"title":"Safety compliance","description":"Fail-safe operation and emergency egress compliance."},{"title":"Testing & handover","description":"Reliability testing under normal and emergency conditions."}]'::jsonb, '["Reliable, secure door operation","Safe, compliant emergency egress","Smooth flow at busy entrances","Hardware built to last"]'::jsonb, '["Electric strikes","Magnetic locks","Automatic doors","Turnstiles","Exit buttons & sensors"]'::jsonb, '["access-control-systems","biometric-systems","intercom-systems","fire-alarm-systems"]'::jsonb, '["corporate","government","healthcare","education","industrial"]'::jsonb, false, 'DoorOpen', 16),
  ('intercom-systems', 'Intercom Systems', cat_access, 'See, speak and grant access from anywhere', 'Audio/video intercoms for gates, receptions and multi-tenant buildings with remote unlock.', 'We deploy audio and video intercom systems for gates, receptions and multi-tenant buildings, with remote unlock and integration into access control.', '["No way to verify visitors before granting access","Staff leaving desks to open gates and doors","Multi-tenant buildings with messy access management","Need to answer the gate from anywhere"]'::jsonb, 'We deploy video and audio intercoms with remote unlock, multi-tenant support and access-control integration.', '[{"title":"Intercom deployment","description":"Audio/video intercoms at gates, doors and receptions."},{"title":"Remote unlock","description":"Grant access from a desk handset, mobile app or video phone."},{"title":"Multi-tenant support","description":"Directory and per-unit calling for apartments and offices."},{"title":"Access integration","description":"Intercom integrated with access control and CCTV."},{"title":"Mobile answering","description":"Answer and unlock from anywhere via app."}]'::jsonb, '["Verify visitors before granting access","Convenience without compromising security","Smooth multi-tenant access","Answer the gate from anywhere"]'::jsonb, '["IP video intercoms","Mobile intercom apps","Multi-tenant directories","Remote unlock"]'::jsonb, '["access-control-systems","door-access-systems","cctv-installation","smart-building-solutions"]'::jsonb, '["residential","corporate","hospitality","education","government"]'::jsonb, false, 'PhoneCall', 17),
  ('burglar-alarm-systems', 'Burglar Alarm Systems', cat_alarm, 'Detect intruders early, before loss occurs', 'Intrusion alarm systems with sensors, sirens and remote alerts for homes and businesses.', 'We design alarm systems with door/window contacts, motion detectors, glass-break sensors and sirens.', '["Theft discovered only after the fact","No alert when an intruder forces entry at night","Alarms that go off with no one to respond","Sensors that false-trigger constantly"]'::jsonb, 'We design alarm systems with the right sensors for your risk, tuned to minimise false alarms and configured to alert the right people fast.', '[{"title":"Sensor design","description":"Contacts, motion, glass-break and vibration sensors at risk points."},{"title":"Control panel","description":"Programmable panel with arm/disarm and zone management."},{"title":"Alerting","description":"Sirens plus phone/app alerts."},{"title":"Tuning","description":"Zone configuration to minimise false alarms."},{"title":"Integration","description":"Link with CCTV, access control and monitoring."}]'::jsonb, '["Early detection of forced entry","Immediate deterrent and response","Remote alerts wherever you are","Lower false-alarm fatigue"]'::jsonb, '["Motion & contact sensors","Glass-break sensors","Control panels","Sirens & strobes","GSM/IP alerting"]'::jsonb, '["cctv-installation","perimeter-intrusion","access-control-systems","fire-alarm-systems","video-monitoring"]'::jsonb, '["residential","retail","warehouse","corporate","industrial"]'::jsonb, false, 'Siren', 18),
  ('fire-alarm-systems', 'Fire Alarm Systems', cat_alarm, 'Life-safety detection engineered to standards', 'Conventional and addressable fire alarm systems with detectors, call points and sounders.', 'We design and install conventional and addressable fire alarm systems with smoke, heat and flame detectors, manual call points, sounders and strobes.', '["No early warning of fire endangering lives","Systems that do not meet safety standards","Undersized sounders that cannot be heard","No integration with access control for evacuation"]'::jsonb, 'We design and install fire alarm systems with proper detector coverage, audible/visual alerting and integration for safe evacuation.', '[{"title":"System design","description":"Detector coverage and zoning engineered to standards."},{"title":"Detector deployment","description":"Smoke, heat and flame detectors at the right locations."},{"title":"Call points & sounders","description":"Manual call points, sounders and strobes for full-site alerting."},{"title":"Panel & programming","description":"Control panel with zones, delays and evacuation logic."},{"title":"Integration","description":"Door release for evacuation and link to monitoring."}]'::jsonb, '["Early reliable fire detection","Compliant insurable life-safety system","Clear evacuation alerting","Integrated, safer response"]'::jsonb, '["Conventional & addressable panels","Smoke/heat/flame detectors","Sounders & strobes","Manual call points"]'::jsonb, '["fire-detection-safety","door-access-systems","burglar-alarm-systems","managed-services"]'::jsonb, '["hospitality","healthcare","education","corporate","industrial","warehouse"]'::jsonb, true, 'Bell', 19),
  ('fire-detection-safety', 'Fire Detection & Safety Systems', cat_alarm, 'Beyond alarms — full fire-safety engineering', 'Comprehensive fire detection, suppression support and safety systems for compliance and protection.', 'We cover the wider fire-safety picture — detection design, suppression support interfaces, emergency lighting, signage and evacuation planning.', '["Partial fire safety with gaps","Emergency lighting that fails when power is lost","No coordinated evacuation plan","Compliance gaps that surface during inspection"]'::jsonb, 'We engineer comprehensive fire detection and safety.', '[{"title":"Detection engineering","description":"Detector selection and coverage for your premises type."},{"title":"Suppression interfaces","description":"Integration with suppression and shutdown systems."},{"title":"Emergency lighting","description":"Lighting that guides evacuation during power loss."},{"title":"Signage & egress","description":"Evacuation signage and exit routing support."},{"title":"Compliance documentation","description":"System records for inspection and insurance."}]'::jsonb, '["Comprehensive compliant fire safety","Safer evacuation under any condition","Reduced liability and insurability","Coordinated documented protection"]'::jsonb, '["Detection systems","Suppression interfaces","Emergency lighting","Evacuation signage"]'::jsonb, '["fire-alarm-systems","door-access-systems","managed-services","server-data-centre"]'::jsonb, '["hospitality","healthcare","education","industrial","warehouse","corporate"]'::jsonb, false, 'Flame', 20),
  ('perimeter-intrusion', 'Perimeter Intrusion Detection', cat_alarm, 'Catch intruders at the fence, not the door', 'Perimeter sensors, beam detectors and fence systems for early intrusion warning.', 'We deploy outdoor perimeter detection — beam sensors, fence detection and vibration sensors — integrated with CCTV and alarms for a layered defence.', '["Intruders detected only after they are inside","Large perimeters that cannot be watched constantly","Need to trigger CCTV recording before entry","Outdoor environments that defeat indoor sensors"]'::jsonb, 'We deploy outdoor perimeter detection integrated with CCTV and alarms for early warning.', '[{"title":"Perimeter assessment","description":"Boundary survey to choose the right detection technology."},{"title":"Sensor deployment","description":"Active/passive beams, fence or vibration sensors."},{"title":"CCTV integration","description":"Triggered recording and PTZ camera response."},{"title":"Alarm & alerts","description":"Sirens and remote alerts on detection."},{"title":"Environmental tuning","description":"Tuning to reduce false triggers from animals and weather."}]'::jsonb, '["Earlier detection at the boundary","Time to respond before entry","Triggered CCTV for evidence","Layered defence with alarms and surveillance"]'::jsonb, '["Active infrared beams","Fence & vibration sensors","Outdoor detectors","CCTV integration"]'::jsonb, '["cctv-installation","burglar-alarm-systems","video-monitoring","access-control-systems"]'::jsonb, '["industrial","warehouse","construction","residential","government"]'::jsonb, false, 'ShieldAlert', 21),
  ('server-data-centre', 'Server & Data-Centre Solutions', cat_infra, 'Resilient compute, storage and racks', 'Server deployment, rack fit-out, storage and backup for reliable business compute.', 'We design and deploy server and small-data-centre solutions — physical and virtual servers, storage, rack fit-out, cooling, UPS and backup.', '["Servers sitting under a desk with no redundancy","No proper rack, cooling or power protection","Data at risk from failed drives with no backup","Recovery that would take days, not hours"]'::jsonb, 'We engineer server and data-centre solutions — compute, storage, racks, UPS and backup — built for resilience and fast recovery.', '[{"title":"Architecture & sizing","description":"Compute, storage and network sized to your workload."},{"title":"Rack & environment","description":"Racks, cooling, cable management and layout."},{"title":"Power & UPS","description":"UPS protection and power distribution."},{"title":"Virtualisation & storage","description":"Hypervisors, RAID storage and capacity planning."},{"title":"Backup & recovery","description":"Backup strategy with tested recovery."}]'::jsonb, '["Reliable business compute","Protected power and cooling","Data protected by backup and redundancy","Faster recovery from failure"]'::jsonb, '["Virtualisation (Hyper-V/Proxmox)","RAID/NAS storage","Racks & UPS","Veeam backup","APC power"]'::jsonb, '["computer-it-support","managed-services","network-security","firewall-endpoint-protection","network-installation"]'::jsonb, '["corporate","finance","healthcare","education","industrial"]'::jsonb, true, 'ServerCog', 22),
  ('computer-it-support', 'Computer & IT Support', cat_infra, 'Responsive IT support that keeps people productive', 'Helpdesk, on-site and remote IT support for workstations, users and day-to-day operations.', 'We provide responsive IT support — remote helpdesk and on-site assistance — covering workstations, users, networking and day-to-day IT.', '["IT issues that stall work for hours or days","No responsive support when something breaks","Recurring problems nobody gets to the root of","Staff wasting time on IT issues instead of their jobs"]'::jsonb, 'We provide responsive remote and on-site IT support — fast helpdesk and root-cause resolution.', '[{"title":"Helpdesk support","description":"Remote support for user and system issues."},{"title":"On-site support","description":"Engineers on-site for hands-on issues."},{"title":"Workstation management","description":"Setup, updates and troubleshooting of computers."},{"title":"User & account support","description":"Account, email and access management."},{"title":"Root-cause resolution","description":"Fixing underlying issues, not just symptoms."}]'::jsonb, '["Faster resolution of IT issues","Less downtime, more productivity","Predictable IT support costs","One number to call for IT"]'::jsonb, '["Remote support tooling","Helpdesk ticketing","Workstation management","User provisioning"]'::jsonb, '["managed-services","server-data-centre","network-maintenance","systems-installation-maintenance"]'::jsonb, '["corporate","smb","education","healthcare","retail"]'::jsonb, false, 'MonitorCog', 23),
  ('systems-installation-maintenance', 'Systems Installation & Maintenance', cat_infra, 'Deployed right, maintained properly', 'Professional installation and ongoing maintenance for IT and security systems.', 'We handle the installation and ongoing maintenance of IT and security systems — making sure everything from servers to access control is deployed to standard and kept healthy over its lifetime.', '["Systems installed without proper configuration","No maintenance so systems degrade and fail","Multiple vendors with no overall ownership","Equipment past warranty with no support path"]'::jsonb, 'We install and maintain your IT and security systems — proper deployment plus scheduled, preventive maintenance.', '[{"title":"Professional installation","description":"Systems deployed, configured and tested to standard."},{"title":"Preventive maintenance","description":"Scheduled servicing to keep systems healthy."},{"title":"Health monitoring","description":"Monitoring that catches issues early."},{"title":"Lifecycle management","description":"Warranty, refresh and replacement planning."},{"title":"Single ownership","description":"One partner accountable across systems."}]'::jsonb, '["Systems that work reliably for longer","Fewer surprise failures","Predictable maintenance costs","One accountable partner"]'::jsonb, '["Installation & commissioning","Preventive maintenance","Monitoring","Lifecycle planning"]'::jsonb, '["managed-services","computer-it-support","network-maintenance","server-data-centre"]'::jsonb, '["corporate","smb","education","healthcare","industrial"]'::jsonb, false, 'Cog', 24),
  ('smart-building-solutions', 'Smart Building Solutions', cat_infra, 'Connected, intelligent buildings', 'Integrated building systems — security, automation, lighting and energy — working as one.', 'We design smart-building solutions that integrate security, access, surveillance, lighting, climate and energy into one manageable platform.', '["A dozen systems that do not talk to each other","Energy waste from unmanaged lighting and climate","No automation for routine building functions","Complexity that frustrates facility teams"]'::jsonb, 'We design integrated smart-building solutions — security, automation and energy under one platform.', '[{"title":"Integration design","description":"Architecture unifying security, automation and energy."},{"title":"Automation","description":"Schedules and rules for lighting, climate and access."},{"title":"Energy management","description":"Monitoring and control to reduce waste."},{"title":"Single platform","description":"One interface for building operations."},{"title":"Scalability","description":"Architecture that grows with the building."}]'::jsonb, '["Simpler, smarter building operations","Lower energy costs","Better security and comfort","One interface instead of many"]'::jsonb, '["Building automation","IoT integration","Lighting & climate control","Unified platforms"]'::jsonb, '["access-control-systems","intercom-systems","cctv-installation","wifi-installation","server-data-centre"]'::jsonb, '["corporate","hospitality","residential","government","healthcare"]'::jsonb, false, 'Building2', 25),
  ('managed-services', 'Managed Services & Technical Support', cat_infra, 'Your IT and security, fully managed', 'Ongoing managed services — monitoring, maintenance, support and improvement — under one agreement.', 'Our managed services put your IT and security under continuous care — monitoring, preventive maintenance, priority support and ongoing improvement.', '["Unpredictable IT and security costs","Systems that degrade because nobody maintains them","Slow, reactive support","No visibility into system health or risk"]'::jsonb, 'We manage your IT and security under one agreement — proactive monitoring, maintenance, support and improvement.', '[{"title":"Continuous monitoring","description":"24/7 monitoring of critical systems and security."},{"title":"Preventive maintenance","description":"Scheduled servicing across IT and security."},{"title":"Priority support","description":"Defined SLAs and direct access to engineers."},{"title":"Reporting & visibility","description":"Regular health and activity reporting."},{"title":"Continuous improvement","description":"Recommendations to strengthen and optimise over time."}]'::jsonb, '["Predictable costs and fewer surprises","Healthier systems that fail less","Faster, prioritised response","Strategic partner, not just a vendor"]'::jsonb, '["Monitoring platforms","RMM tooling","Ticketing & SLAs","Security management"]'::jsonb, '["computer-it-support","network-maintenance","network-security","systems-installation-maintenance"]'::jsonb, '["corporate","smb","finance","healthcare","education"]'::jsonb, true, 'LifeBuoy', 26)
  ON CONFLICT ("slug") DO UPDATE SET "name" = EXCLUDED."name", "categoryId" = EXCLUDED."categoryId", "tagline" = EXCLUDED."tagline", "shortDescription" = EXCLUDED."shortDescription", "overview" = EXCLUDED."overview", "problem" = EXCLUDED."problem", "solution" = EXCLUDED."solution", "deliverables" = EXCLUDED."deliverables", "benefits" = EXCLUDED."benefits", "tech" = EXCLUDED."tech", "relatedServices" = EXCLUDED."relatedServices", "relatedIndustries" = EXCLUDED."relatedIndustries", "featured" = EXCLUDED."featured", "iconName" = EXCLUDED."iconName", "updatedAt" = CURRENT_TIMESTAMP;
END $$;

-- ═══════════════════════════════════════════════════════════
--  DONE!
--
--  Tables created: 12
--  Admin user created: 1 (superadmin)
--  Categories seeded: 6
--  Services seeded: 26
--  Industries seeded: 13
--  Solutions seeded: 6
--  Projects seeded: 9
--  Testimonials seeded: 8
--  FAQs seeded: 16
--  Blog posts seeded: 6
--  Company settings seeded: 1
--
--  LOGIN:
--    URL:      https://allisonglobal.vercel.app/admin/login
--    Email:    admin@allisonglobal.tech
--    Password: Admin@2025
--
--  ⚠️  CHANGE THE PASSWORD after first login!
-- ═══════════════════════════════════════════════════════════
